<aside class="main-sidebar sidebar-dark-primary">
    <!-- Brand Logo -->
    <a class="brand-link">
      <img src="img/logo_nacional.png" alt="nacional tecnologia logo" class="brand-image img-circle bg-white" style="opacity: .8">
      <span class="brand-text font-weight-light">Atendimento</span>
    </a>
    <div class="sidebar">

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
          <li class="nav-item menu-open">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>
                Não atendidos
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>
                atendidos
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
          </li>
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>