<?php
session_start();
$pagina_atual = $_SESSION['pag'] = '/contactus';

?>

<header>
    <!-- Navbar -->
    <nav class="borda-verde navbar navbar-expand-sm navbar-white navbar-light fixed-top">
        <a href="/" class="navbar-brand ml-5">
            <img src="img/logo_nacional.png" alt="logo nacional tecnologia" width="150px">
        </a>
        <button class="navbar-toggler" data-toggle="collapse" data-target="#barra1">
            <i class="fa-solid fa-bars"></i>
        </button>
        <div class="navbar-collapse collapse" id="barra1">
            <!-- Left navbar links -->
            <ul class="navbar-nav">
                <li class="nav-item ">
                    <a href="/" class="nav-link">Início</a>
                </li>
                <li class="nav-item ">
                    <a href="/about-us" class="nav-link">Empresa</a>
                </li>
                <li class="nav-item ">
                    <a href="/pricing" class="nav-link">Planos</a>
                </li>
            </ul>
        </div>
        <ul class="navbar-nav ml-auto">
            <a href="/contactus" class="btn btn-success mr-5">Entre em contato</a>
        </ul>
    </nav>
    <!-- /.navbar -->
</header>
<main class="mt-5">
    <section class="module parallax parallax-2 overlay" id="paralax-contactus">
        <h1 class="display-5 font-weight-bold text-white mt-5 ml-5" style="z-index: 2; color:white">Entre em contato
            </h1>
        </section>
    </main>
    <div class="container">
        <div class="row justify-content-around">
            <div class="col-md-7">
                <p class="mt-5">Entre em contato conosco sobre qualquer coisa relacionada á nossa empresa ou serviços.
                    <br> Retornaremos o mais breve possível
                </p>
                <form action="/processa_dados" method="post">
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label">
                            <p class="font-weight-bold" id="nome">Nome*</p>
                        </label>
                        <div class="col-sm-10">
                            <input class="form-control "  name="nome" type="text">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-2 col-form-label">
                        <p class="font-weight-bold">Telefone*</p>
                    </label>
                    <div class="col-sm-10">
                        <input class="form-control" id="nmrTel" name="telefone" type="tel">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-2 col-form-label">
                        <p class="font-weight-bold">E-mail*</p>
                    </label>
                    <div class="col-sm-10">
                        <input class="form-control " name="email" type="email">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-2 col-form-label">
                        <p class="font-weight-bold">Empresa*</p>
                    </label>
                    <div class="col-sm-10">
                        <input class="form-control" name="empresa" type="text">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-2 col-form-label">
                        <p class="font-weight-bold">Assunto*</p>
                    </label>
                    <div class="col-sm-10">
                        <input class="form-control" name="assunto" type="text">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-2 col-form-label">
                        <p class="font-weight-bold">Pergunta*</p>
                    </label>
                    <div class="col-sm-10">
                        <textarea class="form-control pb-5" name="pergunta" type="text"></textarea>
                    </div>
                </div>
                <button type="submit" class="btn btn-success btn-lg" style="margin-left:17%">Enviar</button>
            </form>
        </div>
        <div class="col-md-4 mt-5">
            <p>Nacional Tecnologia
                <br>
                <i class="fa-solid fa-location-dot"></i> Avenida Nicolas Boer, 399 - 3° Andar
                <br>
                <i class="fa-solid fa-phone"></i> +55 11 2122-4060
                <br>
                <i class="fa-solid fa-envelope"></i> contato@nacionaltecnologia.com.br
            </p>
        </div>
    </div>
</div>
<div class="chat ml-auto text-center mr-3 fixed-bottom mb-4 display " id="chat-click" onmouseenter="clicavel('#chat-click')">
    <a type="button"><i class="fa-solid fa-xl fa-comment-dots mt-4 text-white"></i></a>
</div>
<? if (isset($_GET['mensagem']) && $_GET['mensagem'] == 'enviada') { ?>
    <script>
        $(document).ready(() => {
            $('#modalSucesso').modal('show')
        })
    </script>
<? } ?>
<? if (isset($_GET['preenchimento']) && $_GET['preenchimento'] == 'erro') { ?>
    <script>
        $(document).ready(() => {
            $('#modalErro').modal('show')
        })
    </script>
<? } ?>
<? if (isset($_GET['preenchimento']) && $_GET['preenchimento'] == 'erroEmail') { ?>
    <script>
        $(document).ready(() => {
            $('#modalErroEmail').modal('show')
        })
    </script>
<? } ?>
<?php require_once 'modal.phtml' ?>
<?php require_once 'chat.phtml' ?>