<?php 
    session_start();
    $pagina_atual = $_SESSION['pag'] = '/empresa'
?>
<header>
    <!-- Navbar -->
    <nav class="borda-verde navbar navbar-expand-sm navbar-white navbar-light fixed-top">
        <a href="/" class="navbar-brand ml-5">
            <img src="img/logo_nacional.png" alt="logo nacional tecnologia" width="150px">
        </a>
        <button class="navbar-toggler" data-toggle="collapse" data-target="#barra1">
            <i class="fa-solid fa-bars"></i>
        </button>
        <div class="navbar-collapse collapse" id="barra1">
            <!-- Left navbar links -->
            <ul class="navbar-nav">
                <li class="nav-item ">
                    <a href="/" class="nav-link">Início</a>
                </li>
                <li class="nav-item ">
                    <a href="/about-us" class="nav-link active">Empresa</a>
                </li>
                <li class="nav-item ">
                    <a href="/pricing" class="nav-link">Planos</a>
                </li>
            </ul>
        </div>
        <ul class="navbar-nav ml-auto">
            <a href="/contactus" class="btn btn-success mr-5">Entre em contato</a>
        </ul>
    </nav>
    <!-- /.navbar -->
</header>
<main class="mt-5">
    <section class="module parallax parallax-2 overlay" id="paralax-contactus">
        <h1 class="display-5 font-weight-bold text-white mt-5 ml-5" style="z-index: 2; color:white">Sobre nós</h1>
    </section>
</main>
<section class="mt-5">
    <div class="container">
        <p>A Nacional Tecnologia é uma empresa de tecnologia com 20 anos de experiência no mercado, que conta com uma
            equipe de profissionais qualificados e comprometidos com a inovação e a excelência. </p>
        <p>A empresa oferece soluções personalizadas para pequenas e médias empresas que desejam crescer e se destacar
            em seus segmentos, por meio de um sistema integrado de gestão, comunicação e marketing. </p>
        <p>O sistema da Nacional Tecnologia permite aos clientes otimizar seus processos, reduzir custos, aumentar a
            produtividade, melhorar o relacionamento com os consumidores e ampliar sua presença no mercado digital. </p>
        <p>A Nacional Tecnologia é uma parceira estratégica para o sucesso dos seus clientes, pois entende suas
            necessidades e oferece soluções sob medida, com qualidade, segurança e agilidade. </p>
    </div>
</section>