<main class="mt-5">
    <section class="module parallax parallax-2 overlay" id="paralax-contactus">
        <h1 class="display-5 font-weight-bold text-white mt-5 ml-5" style="z-index: 2; color:white">Sobre nós</h1>
    </section>
</main>
<section class="mt-5">
    <div class="container">
        <p>A Nacional Tecnologia é uma empresa de tecnologia com 20 anos de experiência no mercado, que conta com uma
            equipe de profissionais qualificados e comprometidos com a inovação e a excelência. </p>
        <p>A empresa oferece soluções personalizadas para pequenas e médias empresas que desejam crescer e se destacar
            em seus segmentos, por meio de um sistema integrado de gestão, comunicação e marketing. </p>
        <p>O sistema da Nacional Tecnologia permite aos clientes otimizar seus processos, reduzir custos, aumentar a
            produtividade, melhorar o relacionamento com os consumidores e ampliar sua presença no mercado digital. </p>
        <p>A Nacional Tecnologia é uma parceira estratégica para o sucesso dos seus clientes, pois entende suas
            necessidades e oferece soluções sob medida, com qualidade, segurança e agilidade. </p>
    </div>
</section>