<?php
    session_start(); 
    $pagina_atual = $_SESSION['pag'] = '/'
?>
<main>
    <section class="module parallax parallax-1">
        <h1 class="display-3 font-weight-normal text-center " style="z-index: 2; color:white">Med Nacional Tech</h1>
        <h1 class="display-5 font-weight-bold mt-3 text-center text-white" style="z-index: 2; color:white">Sistema ERP
            para Clínicas e Consultórios</h1>
        <!-- ajustar isso nas medias queries -->
        <a href="/contactus" class="btn btn-success btn-sm mt-5"
            style="width: 10%; margin-left: 42%;z-index: 2; color:white">Entre
            em contato</a>

    </section>
</main>
<main class="container">
    <div class="row mt-5 justify-content-around">
        <div class="col-md-6">
            <h3 class="font-weight-bold text-center">Maximize a eficiência da sua clínica!</h3>
            <h3 class="font-weight-bold text-center mt-3">Med Nacional Tech</h3>
            <p>Gerenciar uma clínica ou consultório médico pode ser um desafio. Entre agendamento de consultas,
                gerenciamento de prontuários de pacientes, controle de estoque de medicamentos e equipamentos, e
                conformidade com regulamentos de saúde, há muitas peças móveis para acompanhar.</p>
            <p>É aqui que entra o nosso sistema de planejamento de recursos empresariais (ERP). Projetado
                especificamente para clínicas e consultórios, nosso ERP oferece uma solução completa para gerenciar
                todos os aspectos do seu negócio.</p>
            <p>Com nosso ERP, você pode:</p>
            <ul>
                <li><strong>Agendar consultas</strong> de maneira eficiente, evitando conflitos de horários e
                    otimizando a utilização de seus recursos.</li>
                <li>Manter <strong> prontuários de pacientes</strong> organizados e acessíveis, melhorando a
                    qualidade do atendimento ao paciente.</li>
                <li>Gerenciar seu <strong>estoque de medicamentos e equipamentos,</strong> garantindo que você nunca
                    fique sem os suprimentos necessários</li>
                <li>Cumprir facilmente com os <strong>regulamentos de saúde,</strong> graças às nossa ferramentas de
                    conformidade integradas.</li>
            </ul>
            <p>Além disso, nosso ERP é fácil de usar e pode ser personalizado para atender às necessidades
                específicas de sua clínica ou consultório. Com nosso ERP, você pode se concentrar no que mais
                importa: fornecer cuidados de alta qualidade aos seus pacientes.</p>
            <a href="/contactus" class="btn btn-success">Saiba mais</a>
        </div>
        <div class="col-md-5 align-self-center">
            <img src="img/cara_computador.jpg">
        </div>
    </div>
</main>
<div class='mt-3' style="background-color: green;">
    <h1 class="display-4 font-weight-bold text-center text-white">Planos</h1>
</div>
<div class="container">
    <div class="row justify-content-around">
        <div class="col-md-4">
            <div class="card ">
                <div class="card-header" style="background-color: rgb(2, 90, 2);">
                    <h3 class="text-white text-center">Iniciante</h3>
                </div>
                <div class="card-body borda-plano" style="background-color: rgb(212, 241, 212);">
                    <p class="text-center">
                        <span class="display-5 font-weight-normal">R$</span>
                        <span class="display-3 font-weight-bold">99</span>
                        <span class="display-5 font-weight-normal">,00</span>
                    <p class="text-center" style="font-size: 12px;"> / mês</p>
                    </p>
                </div>
                <div class="bg-light">
                    <p class="text-center mt-3">Vendas e Faturamento</p>
                    <hr>
                    <p class="text-center">Contatos e Agenda(Integração Google e Microsoft)</p>
                    <hr>
                    <p class="text-center">20 NFSEs Nacional</p>
                    <hr>
                    <p class="text-center">Suporte por Ticket</p>
                </div>
                <div style="background-color: rgb(2, 90, 2);">
                    <div class="row justify-content-center">
                        <a href="/contactus" class="btn btn-success mt-5 mb-5"
                            style="background-color: green;">Iniciar agora</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card">
                <div class="card-header" style="background-color: rgb(2, 90, 2);">
                    <h3 class="text-white text-center">Profissional</h3>
                </div>
                <div class="card-body borda-plano" style="background-color: rgb(212, 241, 212);">
                    <p class="text-center">
                        <span class="display-5 font-weight-normal">R$</span>
                        <span class="display-3 font-weight-bold">169</span>
                        <span class="display-5 font-weight-normal">,00</span>
                    </p>
                    <p class="text-center" style="font-size: 12px;"> / mês</p>
                </div>
                <div class="bg-light">
                    <p class="text-center mt-3">Tudo do Iniciante + </p>
                    <hr>
                    <p class="text-center">CRM completo para equipes de qualquer tamanho</p>
                    <hr>
                    <p class="text-center">NFSEs limitadas</p>
                    <hr>
                    <p class="text-center">Suporte por Ticket e Email</p>
                </div>
                <div style="background-color: rgb(2, 90, 2);">
                    <div class="row justify-content-center">
                        <a href="/contactus" class="btn btn-success mt-5 mb-5"
                            style="background-color: green;">Iniciar agora</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card ">
                <div class="card-header" style="background-color: rgb(2, 90, 2);">
                    <h3 class="text-white text-center">Especialista</h3>
                </div>
                <div class="card-body borda-plano" style="background-color: rgb(212, 241, 212);">
                    <p class="text-center">
                        <span class="display-5 font-weight-normal">R$</span>
                        <span class="display-3 font-weight-bold">275</span>
                        <span class="display-5 font-weight-normal">,00</span>
                    </p>
                    <p class="text-center" style="font-size: 12px;"> / mês</p>
                </div>
                <div class="bg-light">
                    <p class="text-center mt-3">Tudo do Profissional +</p>
                    <hr>
                    <p class="text-center">RH(Recrutamento e Avaliações)</p>
                    <hr>
                    <p class="text-center">Projetos e Marketing (Email Marketing e Pesquisas)</p>
                    <hr>
                    <p class="text-center">Suporte por Ticket, Email e Telefone</p>
                </div>
                <div style="background-color: rgb(2, 90, 2);">
                    <div class="row justify-content-center">
                        <a href="/contactus" class="btn btn-success mt-5 mb-5"
                            style="background-color: green;">Iniciar agora</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php if(isset($_GET['procura'])){
    require_once 'chat.phtml';
}?>
<script>
    $('#chatBox').removeClass('display')
</script>