<?php 
    session_start();
    $pagina_atual = $_SESSION['pag'] = '/pricing';
?>
<header>
    <!-- Navbar -->
    <nav class="borda-verde navbar navbar-expand-sm navbar-white navbar-light fixed-top">
        <a href="/" class="navbar-brand ml-5">
            <img src="img/logo_nacional.png" alt="logo nacional tecnologia" width="150px">
        </a>
        <button class="navbar-toggler" data-toggle="collapse" data-target="#barra1">
            <i class="fa-solid fa-bars"></i>
        </button>
        <div class="navbar-collapse collapse" id="barra1">
            <!-- Left navbar links -->
            <ul class="navbar-nav">
                <li class="nav-item ">
                    <a href="/" class="nav-link">Início</a>
                </li>
                <li class="nav-item ">
                    <a href="/about-us" class="nav-link">Empresa</a>
                </li>
                <li class="nav-item ">
                    <a href="/pricing" class="nav-link active">Planos</a>
                </li>
            </ul>
        </div>
        <ul class="navbar-nav ml-auto">
            <a href="/contactus" class="btn btn-success mr-5">Entre em contato</a>
        </ul>
    </nav>
    <!-- /.navbar -->
</header>
<main class="mt-5">
    <section class="module parallax parallax-2 overlay" id="paralax-contactus">
        <h1 class="display-5 font-weight-bold text-white mt-5 ml-5" style="z-index: 2; color:white">Nossos Planos</h1>
    </section>
</main>
<div class="container mt-5">
    <div class="row justify-content-around">
        <div class="col-md-4">
            <div class="card opaco" id="card1">
                <div class="card-header" style="background-color: rgb(2, 90, 2);">
                    <h3 class="text-white text-center">Iniciante</h3>
                </div>
                <div class="card-body borda-plano" style="background-color: rgb(212, 241, 212);">
                    <p class="text-center">
                        <span class="display-5 font-weight-normal">R$</span>
                        <span class="display-3 font-weight-bold">99</span>
                        <span class="display-5 font-weight-normal">,00</span>
                    <p class="text-center" style="font-size: 12px;"> / mês</p>
                    </p>
                </div>
                <div class="bg-light borda-plano">
                    <p class="text-center mt-3">Vendas e Faturamento</p>
                    <hr>
                    <p class="text-center">Contatos e Agenda(Integração Google e Microsoft)</p>
                    <hr>
                    <p class="text-center">20 NFSEs Nacional</p>
                    <hr>
                    <p class="text-center">Suporte por Ticket</p>
                </div>
                <div style="background-color: rgb(2, 90, 2);">
                    <div class="row justify-content-center">
                        <a href="/contactus" class="btn btn-success mt-5 mb-5"
                            style="background-color: green;">Iniciar agora</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card opaco" id="card2">
                <div class="card-header" style="background-color: rgb(2, 90, 2);">
                    <h3 class="text-white text-center">Profissional</h3>
                </div>
                <div class="card-body borda-plano" style="background-color: rgb(212, 241, 212);">
                    <p class="text-center">
                        <span class="display-5 font-weight-normal">R$</span>
                        <span class="display-3 font-weight-bold">169</span>
                        <span class="display-5 font-weight-normal">,00</span>
                    </p>
                    <p class="text-center" style="font-size: 12px;"> / mês</p>
                </div>
                <div class="bg-light borda-plano">
                    <p class="text-center mt-3">Tudo do Iniciante + </p>
                    <hr>
                    <p class="text-center">CRM completo para equipes de qualquer tamanho</p>
                    <hr>
                    <p class="text-center">NFSEs limitadas</p>
                    <hr>
                    <p class="text-center">Suporte por Ticket e Email</p>
                </div>
                <div style="background-color: rgb(2, 90, 2);">
                    <div class="row justify-content-center">
                        <a href="/contactus" class="btn btn-success mt-5 mb-5"
                            style="background-color: green;">Iniciar agora</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card opaco" id="card3">
                <div class="card-header" style="background-color: rgb(2, 90, 2);">
                    <h3 class="text-white text-center">Especialista</h3>
                </div>
                <div class="card-body borda-plano" style="background-color: rgb(212, 241, 212);">
                    <p class="text-center">
                        <span class="display-5 font-weight-normal">R$</span>
                        <span class="display-3 font-weight-bold">275</span>
                        <span class="display-5 font-weight-normal">,00</span>
                    </p>
                    <p class="text-center" style="font-size: 12px;"> / mês</p>
                </div>
                <div class="bg-light borda-plano">
                    <p class="text-center mt-3">Tudo do Profissional +</p>
                    <hr>
                    <p class="text-center">RH(Recrutamento e Avaliações)</p>
                    <hr>
                    <p class="text-center">Projetos e Marketing (Email Marketing e Pesquisas)</p>
                    <hr>
                    <p class="text-center">Suporte por Ticket, Email e Telefone</p>
                </div>
                <div style="background-color: rgb(2, 90, 2);">
                    <div class="row justify-content-center">
                        <a href="/contactus" class="btn btn-success mt-5 mb-5"
                            style="background-color: green;">Iniciar agora</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?require_once 'chat.phtml'?>
<?if(!isset($_GET['procura'])){?>
    <script>
        $(document).ready(() => {
            $('#limite').slideUp()
        })
    </script>
<?}?>
