<div class='row fixed-bottom' id="chatBox">
    <div class="col-md- ml-auto">
        <div class="card bg-light" style="margin-bottom:0">
            <div class="card-header bg-success">
                    <p class="card-title" style="font-size:13px;margin-left: 0;">Bot de boas vindas</p>
                <a type="button" class="btn btn-tool" data-card-widget="remove" id="sair"
                    onmouseenter="clicavel('#sair')">
                    <i class="fas fa-times mt-2 "></i>
                </a>
            </div>

            <div class="card-body bg-light">
                <!-- para o scroll funcionar, tem que estar referenciando aquis -->
                <div class="direct-chat-messages">
                    <div class="direct-chat-msg">
                        <div class="direct-chat-infos clearfix">
                            <span class="direct-chat-name float-left">Bot de atendimento</span>
                            <span class="direct-chat-timestamp float-right" style="color:rgb(187, 181, 181)">- 2 horas
                                atrás </span>
                        </div>
                        <i class="fa-regular fa-face-smile fa-2x direct-chat-img" style="color:purple"></i>
                        <div class="direct-chat-text" style="background-color: rgb(224, 244, 224);">
                            <small>Bem vindo à nacional tecnologia</small>
                        </div>
                        <div class="direct-chat-text" style="background-color: rgb(224, 244, 224);">
                            <small>O que você está procurando?</small>
                            <a href="/pricing?procura=preco" class="btn btn-outline-success font-weight-bold mb-2"
                                style="font-size: 0.75em; color:black;">Eu tenho uma dúvida sobre o preço</a>
                            <a href="/?procura=documentacao" id="redirecionaIndex"
                                class="btn btn-outline-success font-weight-bold mb-2"
                                style="font-size: 0.75em; color:black;">Estou procurando a sua documentação</a>
                            <a href="<?= $_SESSION['pag'] ?>?procura=olhada" id="redirecionaMesma"
                                class="btn btn-outline-success font-weight-bold "
                                style="font-size: 0.75em; color:black;">Só estou dando uma olhada</a>
                        </div>
                        <? if (isset($_GET['procura'])) { ?>

                            <div class="direct-chat-msg right">
                                <i class="fa-solid fa-user direct-chat-img fa-xl mt-3"></i>
                                <!-- /.direct-chat-img -->
                                <div class="direct-chat-text">
                                    <? if (isset($_GET['procura']) && $_GET['procura'] == 'olhada') { ?>
                                        <script>
                                            $('#chatBox').addClass('display')
                                            $('#chat-click').removeClass('display')
                                        </script>
                                        <small>Só estou dando uma olhada</small>
                                    <? } ?>
                                    <? if ($_GET['procura'] == 'preco') { ?>
                                        <small>
                                            Eu tenho uma dúvida sobre o preço
                                        </small>
                                    <? } ?>
                                    <? if ($_GET['procura'] == 'documentacao') { ?>
                                        <small>
                                            Estou procurando a sua documentação

                                        </small>
                                    <? } ?>
                                </div>
                            </div>
                            <i class="fa-regular fa-face-smile fa-2x direct-chat-img" style="color:purple"></i>
                            <div class="direct-chat-text" id="ancora" style="background-color: rgb(224, 244, 224);">
                                <small class="font-weight-bold">Tcharaaan aqui está! 🌟</small>
                            </div>
                            <div class="direct-chat-text" style="background-color: rgb(224, 244, 224);">
                                <small class="font-weight-bold">Se precisar de mais alguma coisa, fique à vontade para
                                    entrar em contato</small>
                            </div>
                            <script>
                                $(document).ready(function () {
                                    $('.direct-chat-messages').animate({
                                        scrollTop: $('.direct-chat-messages')[0].scrollHeight
                                    }, 1600);
                                });
                            </script>
                            <i class="fa-solid fa-spinner fa-xl mt-4" style="margin-left:25%" id="load"></i>
                            <div class="direct-chat-text display" style="background-color: rgb(224, 244, 224);" id="chat">
                                <small>O que você está procurando?</small>
                                <a href="/pricing?procura=preco" class="btn btn-outline-success font-weight-bold mb-2"
                                    style="font-size: 0.75em; color:black;">Eu tenho uma dúvida sobre o preço</a>
                                <a href="/?procura=documentacao" id="redirecionaIndex"
                                    class="btn btn-outline-success font-weight-bold mb-2"
                                    style="font-size: 0.75em; color:black;">Estou procurando a sua documentação</a>
                                <a href="<?= $_SESSION['pag'] ?>" id="redirecionaMesma"
                                    class="btn btn-outline-success font-weight-bold "
                                    style="font-size: 0.75em; color:black;">Só estou dando uma olhada</a>
                            </div>
                            <script>
                                setTimeout(() => {
                                    $('#load').addClass('display')
                                    $('#chat').removeClass('display')
                                    $('.direct-chat-messages').animate({
                                        scrollTop: $('.direct-chat-messages')[0].scrollHeight
                                    }, 1000);
                                }, 2000)
                            </script>
                        <? } ?>
                    </div>
                </div>
                <!-- /.card-body -->
                <div class="card-footer"
                    style="border-top: 1px gray solid; background-color: rgb(219, 212, 212);margin: 0% -5% -5% -5%;">
                    <small style="margin-left: 30%;">
                        <i>Selecione uma opção acima.</i>
                    </small>
                </div>
                <!-- /.card-footer-->
            </div>
        </div>
    </div>
</div>