<!-- caso dê certo -->
<div class="modal" tabindex="-1" role="dialog" id="modalSucesso" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title text-success">Sucesso</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Email mandado com sucesso, retornaremos o mais breve possível</p>
            </div>
            <div class="modal-footer">
                <a href="<?= $_SESSION['pag'] ?>" type="button" class="btn btn-success">Ok!</a>
            </div>
        </div>
    </div>
</div>
<!-- caso os campos não sejam preenchidos -->
<div class="modal" tabindex="-1" role="dialog" id="modalErro" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title text-danger">Erro!!!</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Por favor preencha todos os campos do formulário</p>
            </div>
            <div class="modal-footer">
                <a href="<?= $_SESSION['pag'] ?>" type="button" class="btn btn-danger">Ok!</a>
            </div>
        </div>
    </div>
</div>
<!-- caso o email esteja com um erro -->
<div class="modal" tabindex="-1" role="dialog" id="modalErroEmail" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title text-danger">Erro!!!</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Email inválido</p>
            </div>
            <div class="modal-footer">
                <a href="<?= $_SESSION['pag'] ?>" type="button" class="btn btn-danger">Ok!</a>
            </div>
        </div>
    </div>
</div>