<html>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Nacional Tecnologia</title>
    <script src="https://cdn.jsdelivr.net/npm/admin-lte@3.2/dist/js/adminlte.min.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/admin-lte@3.2/dist/css/adminlte.min.css">
    <script src="https://code.jquery.com/jquery-3.7.1.min.js"
        integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/3a7cbcc65c.js" crossorigin="anonymous"></script>
    <!-- Bootstrap JS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <link rel="shortcut icon" href="img/favicon.ico" type="image/x-icon">
    <link rel="stylesheet" href="style.css">
    <script src="script/script.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.inputmask/5.0.7/jquery.inputmask.min.js"></script>
</head>

<body>

    <?= $this->content() ?>
    <footer class="mt-5" style="background-color: green;">
        <div class="container">
            <div class="row justify-content-around">
                <div class="col-md-">
                    <div class="row">
                        <div class="col-md-">
                            <h3 class="font-weight-normal mt-5 text-white">Entre em contato</h3> <br>
                            <i class="fa-solid fa-envelope mb-3 text-white"></i> &nbsp; <a
                                style="color: rgb(39, 209, 39);" href="/contactus">contato@nacionaltecnologia.com.br</a> <br>
                            <i class="fa-solid fa-phone mb-3 text-white"></i> <span style="color: rgb(39, 209, 39);">+55
                                11 2122-4060</span>
                        </div>
                    </div>
                </div>
                <div class="col-md-">
                    <div class="row">
                        <div class="col-md-">
                            <h3 class="font-weight-normal mt-5 text-white mb-4">Empresa</h3>
                            <div onmouseenter="$('#localizacao').css('cursor','pointer')"
                                onclick="location.href = 'https://www.google.com/maps/@-23.519786,-46.6802152,3a,90y,101.02h,85t/data=!3m6!1e1!3m4!1s9O4nOgsEsswT2bN7tGi99g!2e0!7i16384!8i8192?coh=205409&entry=ttu'"
                                id="localizacao">
                                <p style="color: rgb(39, 209, 39);">Avenida Nicolas Boer, 399 - 3° Andar</p>
                                <p style="color: rgb(39, 209, 39);"> Jardim das Perdizes - São Paulo - SP</p>
                                <p style="color: rgb(39, 209, 39);"> CEP: 01140-060</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-">
                    <div class="row">
                        <div class="col-md-">
                            <h3 class="font-weight-normal mt-5 text-white">Siga-nos</h3> <br>
                            <i class="mb-4 fa-brands fa-xl fa-facebook text-white"></i><a href="*"
                                style="color: rgb(39, 209, 39);"> Facebook </a><br>
                            <i class="mb-4 fa-brands fa-xl fa-square-twitter text-white"></i><a href="*"
                                style="color: rgb(39, 209, 39);"> Twitter </a> <br>
                            <i class="mb-4 fa-brands fa-xl fa-linkedin text-white"></i><a href="*"
                                style="color: rgb(39, 209, 39);"> Linkedin </a><br>
                            <i class="mb-5 fa-brands fa-xl fa-instagram text-white"></i><a href="*"
                                style="color: rgb(39, 209, 39);"> Instagram</a> <br>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row p-3" style="background-color: rgb(3, 94, 3);">
            <div class="col-md-6 text-center">
                <p style="color: rgba(255, 255, 255, 0.676);">Copyright &copy; Nacional Tecnologia - 2023</p>
            </div>
            <div class="col-md-6 text-center">
                <p style="color: rgba(255, 255, 255, 0.676);">Powered by CLOUD4ERP - Performance e Controle</p>
            </div>
        </div>
    </footer>
</body>

</html>